# Make sure you install vagrant vbguest plugin
# sudo vagrant plugin install vagrant-vbguest
#
# You might need to install development tools first:
# sudo apt-get install build-essential
# or
# sudo yum groupinstall 'Development Tools'

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
end
