execute pathogen#infect()

syntax on " Turn on color syntax highlighting
filetype plugin indent on " Enable filetype detection, enable loading the indent file for specific file types. 

" Line numbering
set number

" Tabs and spaces
set expandtab " Insert spaces insted of tabs
set tabstop=4 " Number of spaces in edit mode that a <Tab> in the file counts for.
set shiftwidth=4 " Number of spases in normal mode inserted with < or >.
set softtabstop=4 " Number of spaces that a <Tab> counts for while performing editing operations, like inserting a <Tab> or using <BS>.

" Ignore case in search
set ignorecase

" Indentation on
set autoindent
